name: Gateway
version: 1.0
main: xyz.refinedev.queue.bukkit.QueuePlugin
authors: [Zowpy]
commands:
  joinqueue:
    aliases:
      - jq
      - jqueue
      - joinq
    description: "Join a queue"
  leavequeue:
    aliases:
      - lq
      - lqueue
      - leaveq
    description: "Leave your current queue"
  pause:
    aliases:
      - pausequeue
      - pq
      - pauseq
      - pqueue
    description: "Pauses/Resumes a specific queue"
