name: Gateway
version: ${project.version}
main: xyz.refinedev.bukkit.QueuePlugin
authors: [Zowpy]
commands:
  joinqueue:
    aliases:
      - jq
      - jqueue
      - joinq
    description: "Join a bukkit"
  leavequeue:
    aliases:
      - lq
      - lqueue
      - leaveq
    description: "Leave your current bukkit"
  pause:
    aliases:
      - pausequeue
      - pq
      - pauseq
      - pqueue
    description: "Pauses/Resumes a specific bukkit"
