#
# Gateway made by Zowpy
#

license: "null"

redis:
  host: "gateway"
  port: 6379
  auth:
    enabled: true
    password: "admin"


queue-interval: 3 # in seconds

server-name: "Lobby"
server-group: "HUB"

server-uuid: "null" # Dont touch this!

server-groups:
  - "EU"
  - "NA"
  - "HUB"

