#
# Gateway made by Zowpy
#

license: "null"

redis:
  host: "gateway"
  port: 6379
  auth:
    enabled: true
    password: "admin"


queue-interval: 3 # in seconds

server-name: "Lobby"
server-group: "HUB"
# Dont touch this!
server-uuid: "null"

# Make sure this is the same in all servers
server-groups:
  - "EU"
  - "NA"
  - "HUB"

queues:
  practice:
    paused: false
    ip: 34.88.67.102
    port: 25500
    bungee: "practice"
